version: '3.7'
services:

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    healthcheck:
      test: echo stat | nc localhost 2181
      interval: 10s
      timeout: 10s
      retries: 3
    environment:
      - ZOOKEEPER_SERVER_ID=1
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_INIT_LIMIT=5
      - ZOOKEEPER_SYNC_LIMIT=2
      - ZOOKEEPER_SERVERS=zookeeper:2888:3888
    restart: unless-stopped

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    ports:
      - "9091:9091"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9091
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9091
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_BROKER_ID=1
      - BOOTSTRAP_SERVERS=kafka:9091
      - ZOOKEEPER=zookeeper:2181
      - KAFKA_LOG_RETENTION_MS=-1
      - KAFKA_LOG_RETENTION_HOURS=-1
    volumes:
      - ./kafka/kafka1:/var/lib/kafka/data
    restart: unless-stopped
